### PR TITLE
Set code block language when pasting into editor

### LINKED ISSUE #125: Block Editor paste from Markdown does not include code language
### To reproduce:

Create a new post using the Block Editor.

Paste the following text into the Block Editor:

    ### Some markdown

    ```python
    call_function()

    if some_condition:
        do_something()
    ```

Notice that the Python code has been converted into a SyntaxHighlighter Code block, but its language has not been set to `python`.

See the original report [here](https://wordpress.org/support/topic/markdown-language-tags-are-not-supported/), but note that it doesn't not appear to depend on Jetpack.

### PR DESCRIPTION
**Pull request by donnapep**
Fixes #125.

### Changes proposed in this Pull Request

Adds support for language when pasting code into the block editor.

### Testing instructions

Test with the following snippets and ensure the language in the block toolbar is set appropriately. The starting and ending backticks, as well as the language, should not appear as part of the code block content:

    ```python
    call_function()

    if some_condition:
        do_something()
    ```
And:

    ```css
    #button {
      border: none;
    }
    ```

Also test without the language parameter. The backticks should still be removed:

    ```
    #button {
      border: none;
    }
    ```

### CODE REVIEW

File: src/code-block/transforms.js [hunk 1]
```diff
@@ -21,6 +21,16 @@ export default {
 				node.children.length === 1 &&
 				node.firstChild.nodeName === 'CODE'
 			),
+			transform( node ) {
+				const content = node.firstChild.textContent;
+				const [ startingMatch, language ] = content.match( /^```(\w+)?\n/ ) || [ null, null ];
+				const attributes = language ? { language } : {};
+
+				// Extract content without backticks and (optionally) language.
+				attributes.content = startingMatch ? content.replace( startingMatch, '' ).replace( /```$/, '' ) : content;
```
Comment (yscik) [inline src/code-block/transforms.js]: The closing backticks were not removed when some whitespace gets in there — which also seems to happen when more than a single block is pasted. To test, I just copy-pasted the entire description from this PR as one.

Allowing some whitespace in the regexp seems to fix it:

```suggestion
				attributes.content = startingMatch ? content.replace( startingMatch, '' ).replace( /```\s*$/, '' ) : content;
```

**Review by yscik — COMMENTED** [review]
Looks good & works well, just a small issue:

**Review by yscik — APPROVED** [review]
✅
