### PR TITLE
Display the list of available brushes

### LINKED ISSUE #207: Add list of supported tags
### Steps to Reproduce
1. Go to 'Settings page'
2. Try to figure out which tags are supported
3. Click on the link "Click here for a list of valid tags (under "aliases")."
4. Notice that the page displayed is some sort of PDF compression service now

### What I Expected
I wanted to figure out if there is a JSON tag.
The "Click here for a list of valid tags" link points to http://alexgorbatchev.com/SyntaxHighlighter/manual/brushes/ which now gets redirected to https://gogopdf.com/blog/Alex-Gorbatchev-And-gogopdf-Turn-Raw-Javascript-To-A-PDF-Service
It looks like the domain was registered by another organization. 
It may be necessary to remove all references to it from this repository.

### PHP / WordPress / SyntaxHighlighter Evolved version

SyntaxHighlighter Evolved 3.6.0

### PR DESCRIPTION
**Pull request by merkushin**
These brushes could be used as shortcodes instead of passing them to lang property.

Previously, this list was available on the external website but now is not reachable anymore.

Fixes #207 

### Changes proposed in this Pull Request

* Remove external link (the website redirects to another project now).
* Add a list of available tags.

### Testing instructions

* Install and activate SyntaxHighlighter Evolved.
* Go to Settings -> SyntaxHighlighter.
* Find Shortcode Parameters.

### Screenshot / Video
Before:
CleanShot 2021-11-15 at 13 59 19@2x

After:
CleanShot 2021-11-15 at 13 52 54@2x

### CODE REVIEW

**Comment by merkushin** [comment]
Hey @renatho! I see Travis-CI checks don't work. Maybe add some GH actions-based checks?

File: syntaxhighlighter.php [hunk 1]
```diff
@@ -1594,13 +1594,13 @@ function settings_page() { ?>
 					sprintf(
 						// translators: %1$s Lang parameter; %2$s Language parameter; %3$s Valid tags link.
```
Comment (renatho) [inline syntaxhighlighter.php]: I think we should also update this comment too, right?

**Review by renatho — COMMENTED** [review]
> Maybe add some GH actions-based checks?

Hum! Yep! It would be awesome to make this migration like our other repos. You could create a separate PR since it's not related to this though. ;)

**Review by renatho — APPROVED** [review]
🚀
