### PR TITLE
Migrate project to wp-scripts and fix lodash deps

### LINKED ISSUE #267: Syntaxhighlighter block broken on Wordpress 6.4.1
### Steps to Reproduce
1. Go to editor
2. Click on add
...

### What Happened Instead
"Your site doesn’t include support for the SyntaxHighlighter Evolved block. You can try installing the block, convert it to a Custom HTML block, or remove it entirely."

### PHP / WordPress / SyntaxHighlighter Evolved version
Wordpress 6.4.1
Theme Radiate - 1.4.1
SyntaxHighlighter Evolved version 3.6.2

### Browser / OS version
Chrome 119.0.6045.124 / Win 11 (10.0.22631.2428)

### Screenshot / Video
Same problem: https://wordpress.org/support/topic/your-site-doesnt-include-support-for-the-syntaxhighlighter-evolved-block-2/

image

### PR DESCRIPTION
**Pull request by thedebian**
Fixes #267 

### Changes proposed in this Pull Request

* Migrate project from cgb-scripts to wp-scripts
* Fix lodash deps

### Testing instructions

* Checkout the project
* `npm run build`
* Create a new post and add a syntaxhighlighter/code block
* ✅ Should work
* Play with it a bit and check preview
* ✅ Should work
* Install the plugin from the generated zip file and do the same test procedure
* ✅ Should work

### CODE REVIEW

File: src/toolbar-dropdown/index.js [hunk 1]
```diff
@@ -63,15 +60,16 @@ const ToolbarDropdown = ( {
 						{ options.map( ( option ) => {
 							const isSelected =
 								option.value === selectedOption.value;
+							let itemClassNames = 'syntaxhighlighter-toolbar-dropdown__option';
+							if ( isSelected ) {
+								itemClassNames += ' is-selected';
+							}
```
Comment (jgcaruso) [inline src/toolbar-dropdown/index.js:66]: Just curious why `classnames` needed to be removed? Personally I think its cleaner to use that instead of manual string building, from a readability perspective.

**Review by jgcaruso — APPROVED** [review]
Tested the installed plugin and it continues to work! No console errors noticed.

File: src/toolbar-dropdown/index.js (hunk 1 above)
Comment (thedebian) [reply src/toolbar-dropdown/index.js:66]: It was in order to clean up dependencies for things marginally used, seems a bit overkill to use a 3rd party npm package to do a string concatenation ... once 😅

Comment (jgcaruso) [reply src/toolbar-dropdown/index.js:66]: > once

Good point!
