### PR TITLE
Fix nested shortcode bugs

### LINKED ISSUE #32: Nested shortcode problem
Hi,

Can somebody help me with this issue:

```
[code]

[xml]

[/code]
```

output:

```
1
```

should be:

```
[xml]
```

this works:

```
[code]

[[xml]]

[/code]
```

It seems to be the same issue as here: https://github.com/Viper007Bond/syntaxhighlighter/issues/26
Instead of [c] it's [xml].

Is there way to fix f.g. tell Wordpress not to parse shortcodes inside code blocks?

The source for this could be: https://github.com/Viper007Bond/syntaxhighlighter/search?q=do_shortcode&ref=cmdform

This functions allows you to parse nested shortcodes:
http://www.sitepoint.com/wordpress-nested-shortcodes/

### PR DESCRIPTION
**Pull request by gogdzl**
Fixes #32,  #26 and #71 - Fix nested shortcode bugs

This PR addresses issue #32 (Nested shortcode problem). It ensures the plugin doesn't run its own shortcodes multiple times and corrects the original escape method used to replace open square bracket symbols. The original method replaced the `[` symbols with `&#91;` to prevent nested shortcodes from running. However, as indicated in the docs (https://developer.wordpress.org/reference/functions/do_shortcode/ and https://developer.wordpress.org/reference/functions/unescape_invalid_shortcodes/), `&#91;` is converted back to `[`. To address this, we've changed `&#91;` to `&#x5B;`. This modification resolves the issue while preserving the initial escape intention.

Additionally, this PR solves issues #26 and #71 by relying on WordPress's shortcode parsing. This lets SyntaxHighlighter's shortcode strings (e.g., [c]) be used within other shortcodes without interference from SyntaxHighlighter. This solution aims to prevent compatibility issues as illustrated in #71.

The solution proposed for #26 and #71 is somewhat intrusive, as it rewrites the shortcode strings for all shortcodes other than SyntaxHighlighter's. I've considered various scenarios and believe the logic to be robust against edge cases: 

- **Nested shortcodes** - WordPress is tasked with handling these, ensuring only the outermost shortcodes are parsed.
- **Attribute Formatting** - Attributes might use either single or double quotes. This PR transitions all to double quotes and employs esc_attr for attribute escaping. Additional testing is encouraged, though this method has been robust in my tests.
- **Self-closing Shortcodes** - The PR converts self-closing shortcodes to standard format (e.g., [shortcode] and [shortcode/] become [shortcode][/shortcode]). WordPress treats both in the same manner.

If the fix to #26 and #71 is deemed to be too intrusive, the first two commits fix #32. Nonetheless, I believe the code here is as safe as the rest of SyntaxHighlighter's code when it comes to compatibility.

## Changes proposed in this Pull Request ##

- Prevent SyntaxHighlighter's shortcodes from running multiple times.
- Fix the nested shortcodes escape method within shortcode_callback.
- Allow other shortcodes to contain SyntaxHighlighter's shortcode strings (e.g., `[c]`).

## Testing instructions ##

To test instructions from #260 can be used.

As an aditional test this shortcode structure can be used:

```
function attribute_testing_shortcode( $atts ) {
    $a = shortcode_atts( array(
        'att1' => '',
        'att2' => '',
        'att3' => '',
    ), $atts );

    $response = '';
    if ( ! empty( $a['att1'] ) ) {
        $response .= ' ' . $a['att1'];
    }
    if ( ! empty( $a['att2'] ) ) {
        $response .= ' ' . $a['att2'];
    }
    if ( ! empty( $a['att3'] ) ) {
        $response .= ' ' . $a['att3'];
    }
    return $response;
}
add_shortcode( 'attribute_testing', 'attribute_testing_shortcode' );
```

```
<!-- wp:shortcode -->
[c] int i = data[c]; [/c]
<!-- /wp:shortcode -->

<!-- wp:shortcode -->
[attribute_testing att1=one att2='two"' att3="three'''" ]
<!-- /wp:shortcode -->

<!-- wp:shortcode -->
[yell] Yelling data[c] [/yell]
<!-- /wp:shortcode -->

<!-- wp:shortcode -->
[yell] [[c]] [/yell]
<!-- /wp:shortcode -->
```

### CODE REVIEW

File: syntaxhighlighter.php [hunk 1]
```diff
@@ -659,16 +659,21 @@ function shortcode_hack( $content, $callback, $ignore_html = true ) {
...
 			add_shortcode( $shortcode, $callback );
 		}
 
-		$regex = '/' . get_shortcode_regex( $this->shortcodes ) . '/';
+		// Register all other shortcodes, ensuring their content remains unchanged using yet another hack.
+		foreach ( $orig_shortcode_tags as $shortcode_tagname => $shortcode ) {
+			add_shortcode( $shortcode_tagname, array( $this, 'return_entire_shortcode_callback' ) );
+		}
+
+		$regex = '/' . get_shortcode_regex( array_merge( $this->shortcodes, array_keys( $orig_shortcode_tags ) ) ) . '/';
```
Comment (fjorgemota) [inline syntaxhighlighter.php]: Wouldn't this be effectively return the same result as if it didn't have any parameters?

I'm asking because `get_shortcode_regex` by default gets the keys from the global `$shortcode_tags`, and here we have both the shortcodes from `$this->shortcodes`a well as all the shortcodes from the original `$shortcode_tags`, so IMHO the result should be quite similar.

File: syntaxhighlighter.php [hunk 2]
```diff
@@ -749,6 +754,44 @@ function shortcode_hack_extra_escape_escaped_shortcodes_and_parse( $match ) {
...
+			}
+		}
+ 
+		$shortcode_string .= ']';
+
+		if ( $content !== null ) {
+			$shortcode_string .= $content . '[/' . $tag . ']';
+		}
+		return $shortcode_string;
+	}
```
Comment (fjorgemota) [inline syntaxhighlighter.php]: As someone that almost came close to this while working on #260, I must ask:

WDYT if, instead of trying to re-create the shortcode content in a shortcode callback, we force the escape on the shortcodes outside `$this->shortcodes` in `shortcode_hack_extra_escape_escaped_shortcodes`?

I'm just a bit worried that this might cause weird conflicts with other plugins, especially as the fact that shortcodes rely on regex..

File: syntaxhighlighter.php [hunk 3]
```diff
@@ -1377,7 +1420,7 @@ function shortcode_callback( $atts, $code = '', $tag = false ) {
 		$code = ( false === strpos( $code, '<' ) && false === strpos( $code, '>' ) && 2 == $this->get_code_format( $post ) ) ? strip_tags( $code ) : htmlspecialchars( $code );
 
 		// Escape shortcodes
-		$code = preg_replace( '/\[/', '&#91;', $code );
+		$code = preg_replace( '/\[/', '&#x5B;', $code );
```
Comment (fjorgemota) [inline syntaxhighlighter.php:1404]: This is a pretty smart solution! Thanks!

**Review by fjorgemota — COMMENTED** [review]
Hey @gogdzl, this is a pretty smart PR. Thanks for that!

I submitted an early code review. I didn't test the approach yet, but it is looking pretty good from the code changes I saw.

File: syntaxhighlighter.php (hunk 1 above)
Comment (gogdzl) [reply syntaxhighlighter.php]: You are 100% right. I wasn't aware that by default `get_shortcode_regex` returned all registered shortcodes. Since we are adding them all, the result is the same. We should remove the parameter.

File: syntaxhighlighter.php (hunk 2 above)
Comment (gogdzl) [reply syntaxhighlighter.php]: >  WDYT if, instead of trying to re-create the shortcode content in a shortcode callback, we force the escape on the shortcodes outside $this->shortcodes in shortcode_hack_extra_escape_escaped_shortcodes?

I considered an approach similar to what you described. However, it introduced even more edge cases to handle. That's why I opted to rewrite everything, letting WordPress manage the registered shortcodes/nested shortcodes.

> I'm just a bit worried that this might cause weird conflicts with other plugins, especially as the fact that shortcodes rely on regex..

As I highlighted in the PR description, I recognize that this is an intrusive approach. I took extra care during the implementation to address the edge cases specified in the description, and based on my findings, it seems like it won't break anything.

I share your concerns about potential conflicts. If this is deemed too intrusive, one alternative could be introducing a new setting to exclude all shortcodes except for `[code]`. The idea of removing `[c]` was even discussed in https://github.com/Automattic/syntaxhighlighter/issues/72. To address @Viper007Bond's concerns about breaking sites (https://github.com/Automattic/syntaxhighlighter/issues/71), we could activate this shortcode removal only when the setting is enabled, keeping it off by default.

File: syntaxhighlighter.php (hunk 1 above)
Comment (gogdzl) [reply syntaxhighlighter.php]: Removed in 736f10a.

File: syntaxhighlighter.php (hunk 2 above)
Comment (gogdzl) [reply syntaxhighlighter.php]: As we discussed, a less intrusive method was employed in cefde48. Thanks for pointing out the existence of `pre_do_shortcode_tag`!

Comment (fjorgemota) [reply syntaxhighlighter.php]: Great, thanks!

**Review by fjorgemota — COMMENTED** [review]
Hey there. This is looking pretty good, thanks for the changes!

Testing with this snippet of good old C code: 

```c
#include <stdio.h>
int main() {
    char** data = {"hello world"};
    int c = 0;
    printf(data[c]);
    return 0;
    // A [current_datetime]
    // B [[current_datetime]]
    // C [[c]]
    // D [yell]is this yelling?[/yell]
    // E [[yell]]hey there??[[/yell]]
    // F [code language="c"]hey there[/code]
}
```

I found out that this approach works well with shortcodes, but unfortunately not yet with blocks. Here's what I see using shortcodes:

syntaxhighlighter shortcode

And here's the code highlighted using the block:

syntaxhighlighter block

Any ideas on how to solve this? Maybe should we treat this as a different issue? Not sure.

**Comment by gogdzl** [comment]
> Any ideas on how to solve this? Maybe should we treat this as a different issue? Not sure.

This is an entirely different bug. It's one of the issues I mentioned in the comment I left in #260:

> Additionally, I stumbled upon some unreported bugs when mixing blocks and shortcodes. I'll be opening detailed issues about those later.

But I haven't got the chance to create detailed issues to report them.

**Comment by fjorgemota** [comment]
Sounds good, thanks!

@aaronfc @jom Could any of you please test if this PR fixes the cases you tested on #260, please? I tested it here and it seems to be working well, but I'd love to have a second look at this. Thanks!

File: syntaxhighlighter.php [hunk 4]
```diff
@@ -659,16 +677,22 @@ function shortcode_hack( $content, $callback, $ignore_html = true ) {
...
 		// Register all of this plugin's shortcodes
 		foreach ( $this->shortcodes as $shortcode ) {
 			add_shortcode( $shortcode, $callback );
 		}
 
-		$regex = '/' . get_shortcode_regex( $this->shortcodes ) . '/';
+		// Register all other shortcodes, ensuring their content remains unchanged using yet another hack.
+		foreach ( $orig_shortcode_tags as $shortcode_tagname => $shortcode ) {
+			add_shortcode( $shortcode_tagname, '__return_empty_string' );
+			add_filter( 'pre_do_shortcode_tag', array( $this, 'pre_do_shortcode_shortcode_hack_skip_others' ), 10, 4 );
```
Comment (aaronfc) [inline syntaxhighlighter.php]: Is this running once per shortcode on purpose? I don't understand why.

**Review by aaronfc — COMMENTED** [review]
Hey, thank you @gogdzl for working on this unique beast :)

I went on a rabbit hole while testing but I think I can say:
- I could not find any **new** bugs (that were not also happening on `master`).
- The issue #32 is fixed.

Since 4 pairs (of pairs) of eyes are better than 3... @jom can you give this a quick look?

File: syntaxhighlighter.php (hunk 4 above)
Comment (gogdzl) [reply syntaxhighlighter.php]: Because I made a small mistake there. We should be adding filters just once, thanks for catching that. Fixed this in https://github.com/Automattic/syntaxhighlighter/pull/261/commits/392bfae4dfc2860f061c87708845bd840b101dc7.

**Review by jom — APPROVED** [review]
Thanks for your work on this @gogdzl! I think this looks good and works well as a fix for #32.

In my tests, it didn't fix #26 and #71.

For #71:
```html
<!-- wp:html -->
<script>
alert("boom[c]");
</script>
<!-- /wp:html -->
```

This shows an alert with just "boom".

For #26:
```html
<!-- wp:syntaxhighlighter/code {"language":"cpp"} -->
<pre class="wp-block-syntaxhighlighter-code">char data[100];
int cpp;

for (c=0;c&lt;100;c++) {
   data[c]="a";
}</pre>
<!-- /wp:syntaxhighlighter/code -->

<!-- wp:shortcode -->
[code language="cpp"]
char data[100];
int cpp;

for (c=0;c<100;c++) {
   data[c]="a";
}
[/code]
<!-- /wp:shortcode -->
```
The shortcode version just [still] breaks badly and the block renders as `data="a";`.

Since this does fix #32 and like @aaronfc couldn't find any regressions, I think we can merge! Thanks again, @gogdzl.

**Comment by fjorgemota** [comment]
Given that @gogdzl is on WCUS and that this PR is approved, I'll merge this. Thanks for the PR, again, @gogdzl! And thanks @jom and @aaronfc  for the extra review!
